apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: frontendconfigs.networking.gke.io
spec:
  group: networking.gke.io
  names:
    kind: FrontendConfig
    listKind: FrontendConfigList
    plural: frontendconfigs
    singular: frontendconfig
    redirectToHttps:
      enabled: true
  scope: Namespaced
  versions:
    - name: v1beta1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                redirectToHttps:
                  type: object
                  properties:
                    enabled:
                      type: boolean
                    responseCodeName:
                      type: string
                      enum:
                        - MOVED_PERMANENTLY_DEFAULT
                        - FOUND
                        - TEMPORARY_REDIRECT
                        - PERMANENT_REDIRECT
                sslPolicy:
                  type: string
