apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: ingress-backendconfig
  namespace: default
spec:
  healthCheck:
    checkIntervalSec: 30
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 10
  timeoutSec: 30
  connectionDraining:
    drainingTimeoutSec: 60
  securityPolicy:
    name: my-security-policy